"""
email_tool.py
Week 7, Day 4, Task 2 (+ Task 4 retry/failure handling)

Sends booking/reschedule/cancellation notification emails via Gmail SMTP.

Retry/failure handling (Task 4): the actual SMTP send goes through
_send_with_retry, which retries up to 3 times with exponential backoff
on transient connection failures (dropped connection, timeout, DNS).
A permanent failure (bad credentials, malformed address) is not
retried — it fails immediately.
"""

import os
import smtplib
from email.message import EmailMessage
from dotenv import load_dotenv, find_dotenv

from retry_utils import retry_with_backoff

load_dotenv(find_dotenv())

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = 587

RECIPIENT_OVERRIDE = "raniashoaib89@gmail.com"


@retry_with_backoff(max_attempts=3, base_delay=1.0)
def _send_with_retry(msg: EmailMessage, smtp_email: str, smtp_app_password: str):
    """The actual network call — isolated so retry logic lives in one place."""
    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.starttls()
        server.login(smtp_email, smtp_app_password)
        server.send_message(msg)


def _build_and_send(subject: str, body_lines: list[str]) -> dict:
    """Shared send path for all three notification types below."""
    smtp_email = os.environ.get("SMTP_EMAIL")
    smtp_app_password = os.environ.get("SMTP_APP_PASSWORD")
    if not smtp_email or not smtp_app_password:
        return {"success": False, "error": "SMTP_EMAIL or SMTP_APP_PASSWORD not found in .env"}

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = smtp_email
    msg["To"] = RECIPIENT_OVERRIDE
    msg.set_content("\n".join(body_lines))

    try:
        _send_with_retry(msg, smtp_email, smtp_app_password)
        return {"success": True}
    except Exception as e:
        return {"success": False, "error": str(e)}


def send_booking_notification(
    employee_email: str, employee_name: str, client_name: str, client_phone: str,
    property_name: str, date: str, start_time: str, end_time: str, requirements: str = "",
) -> dict:
    subject = f"New Property Visit Booked — {client_name} — {date} {start_time}"
    body_lines = [
        f"Hi {employee_name},", "",
        "A new property visit has been booked for you via the voice agent.", "",
        "MEETING DETAILS", f"Date: {date}", f"Time: {start_time} - {end_time}",
        f"Property: {property_name}", "",
        "CLIENT DETAILS", f"Name: {client_name}", f"Phone: {client_phone}",
    ]
    if requirements:
        body_lines += ["", "CLIENT REQUIREMENTS", requirements]
    body_lines += ["", "— Automatically generated by RealEstate Hub Voice Agent"]
    return _build_and_send(subject, body_lines)


def send_reschedule_notification(
    employee_email: str, employee_name: str, client_name: str, client_phone: str,
    property_name: str, old_date: str, old_start: str, old_end: str,
    new_date: str, new_start: str, new_end: str, requirements: str = "",
) -> dict:
    subject = f"Rescheduled Property Visit — {client_name} — {new_date} {new_start}"
    body_lines = [
        f"Hi {employee_name},", "",
        "A property visit assigned to you has been rescheduled.", "",
        "OLD SCHEDULE", f"Date: {old_date}", f"Time: {old_start} - {old_end}", "",
        "NEW SCHEDULE", f"Date: {new_date}", f"Time: {new_start} - {new_end}", "",
        "PROPERTY", f"{property_name}", "",
        "CLIENT DETAILS", f"Name: {client_name}", f"Phone: {client_phone}",
    ]
    if requirements:
        body_lines += ["", "CLIENT REQUIREMENTS", requirements]
    body_lines += ["", "— Automatically generated by RealEstate Hub Voice Agent"]
    return _build_and_send(subject, body_lines)


def send_cancellation_notification(
    employee_email: str, employee_name: str, client_name: str, client_phone: str,
    property_name: str, date: str, start_time: str, end_time: str, reason: str = "",
) -> dict:
    subject = f"Cancelled Property Visit — {client_name} — {date} {start_time}"
    body_lines = [
        f"Hi {employee_name},", "",
        "A property visit assigned to you has been cancelled.", "",
        "SCHEDULE", f"Date: {date}", f"Time: {start_time} - {end_time}", "",
        "PROPERTY", f"{property_name}", "",
        "CLIENT DETAILS", f"Name: {client_name}", f"Phone: {client_phone}",
    ]
    if reason:
        body_lines += ["", "CANCELLATION REASON", reason]
    body_lines += ["", "— Automatically generated by RealEstate Hub Voice Agent"]
    return _build_and_send(subject, body_lines)


if __name__ == "__main__":
    print("Sending a test booking notification email...")
    result = send_booking_notification(
        employee_email=RECIPIENT_OVERRIDE, employee_name="Test Employee",
        client_name="Test Client", client_phone="0300-1234567",
        property_name="DHA Phase 5, Plot 24-C", date="2026-08-06",
        start_time="15:00", end_time="15:30",
        requirements="3 bedroom, budget 2.5 crore, wants gym and swimming pool",
    )
    if result["success"]:
        print("Email sent successfully. Check your inbox.")
    else:
        print(f"FAILED: {result['error']}")